version: '3'
services:
    ubuntu:
        build:
            context: docker/build/
        volumes:
            - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/config/php-fpm/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
            - ./docker/config/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/config/home/www/.bashrc:/home/www/.bashrc
            # - ./docker/config/home/www/.bash_history:/home/www/.bash_history
            - ./docker/server/nginx:/var/html/log
            - ./docker/server/supervisor:/var/log/supervisor
            - ./app:/var/www/html
        expose:
            - 80
        links:
          - mysql
          - firefox
        networks:
            self:
                ipv4_address: ${NGINX_HOST}
    mysql:
        image: mysql:5.7.20
        environment:
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
        volumes:
        - ./docker/server/mysql:/var/lib/mysql
        networks:
            self:
                ipv4_address: ${MYSQL_HOST}
    firefox:
        image: selenium/standalone-firefox:3.14.0
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
        networks:
            self:
                ipv4_address: 172.73.254.4
networks:
    self:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}