version: '3'
services:
    ubuntu:
        build:
            context: docker/build/
        volumes:
            - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/config/php-fpm/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
            - ./docker/config/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/server/nginx:/var/html/log
            - ./:/var/www/html
        expose:
          - 80
        networks:
            self:
                ipv4_address: ${NGINX_HOST}
networks:
    self:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}